name: Comment on PR if Tests Fail

on:
  workflow_run:
    workflows: ["CI/CD Pipeline"]  # Nome do workflow principal
    types:
      - completed

jobs:
  comment:
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    runs-on: ubuntu-latest

    steps:
      - name: Comment on PR
        uses: actions/github-script@v6
        with:
          script: |
            const { owner, repo } = context.repo;
            const pull_number = context.payload.workflow_run.pull_requests[0].number;
            const body = 'The build has failed. Please check the logs and fix the issues before merging.';
            await github.rest.issues.createComment({
              owner,
              repo,
