name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Cache Python Dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-python-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-python-

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Robot Framework Tests
        run: |
          robot --outputdir results tests/
        continue-on-error: true  # Continua mesmo se os testes falharem

      - name: Upload Test Reports
        uses: actions/upload-artifact@v3
        with:
          name: test-reports
          path: results/

      - name: Create Issue if Tests Fail
        if: always()  # Executa sempre, independentemente do sucesso ou falha
        uses: actions/github-script@v6
        with:
          script: |
            const fs = require('fs');
            const path = require('path');

            try {
              // Lendo o arquivo output.xml
              const xmlFilePath = path.join(process.env.GITHUB_WORKSPACE, 'results', 'output.xml');
              const xmlContent = fs.existsSync(xmlFilePath) ? fs.readFileSync(xmlFilePath, 'utf8') : null;

              // Verifica se o arquivo output.xml foi encontrado e tem conteúdo
              if (!xmlContent || xmlContent.trim() === '') {
                console.log('⚠️ Arquivo output.xml não encontrado ou está vazio. Não será criada uma issue.');
                return;
              }

              // Procurando por mensagens de falha no XML
              const failRegex = /<status status="FAIL".*?>\s*(.*?)\s*<\/status>/gi;
              let match;
              let failText = '';

              while ((match = failRegex.exec(xmlContent)) !== null) {
                failText += `💥 ${match[1].trim()}\n\n`;
              }

              // Se não houver falhas, não cria a issue
              if (!failText) {
                console.log('🎉 Todos os testes passaram. Não será criada uma issue.');
                return;
              }

              // Configuração dos detalhes da issue
              const issueTitle = `⚠️ Testes falharam em ${context.workflow} - ${new Date().toISOString()}`;

              // Limite de caracteres para o corpo da issue
              const characterLimit = 15000;

              // Criar corpo da issue com os detalhes dos erros
              const issueBody = `
                ## 🛑 Detalhes do Erro

                **⚠️ Logs contendo "FAIL":**
                \`\`\`
                ${failText.slice(0, characterLimit)}
                \`\`\`

                🚀 **Ação Recomendada:** Verifique os logs acima para identificar e corrigir os erros. Vamos melhorar esses testes! 💪
              `;

              // Criar a issue no repositório
              await github.rest.issues.create({
                owner: context.repo.owner,
                repo: context.repo.repo,
                title: issueTitle,
                body: issueBody,
                labels: ['bug', 'automated test failure'],
              });
            } catch (error) {
              console.log('❌ Erro ao processar o arquivo XML ou criar a issue:', error.message);
            }
              issue_number: pull_number,
              body,
            });
